<a href="https://colab.research.google.com/github/arvind-maurya/Linear-Algebra/blob/main/AIML_CEP_LA_IRIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra - Motivation by an application#

Let us consider the $\textit{wine}$ data set from scikit-learn package. Let us load the data set and analyze its structure. 

We shall check the following:



1.   Number of instances (or samples)
2.   Number of attributes (or features)
3.   Description of attributes 
4.   Type of class labels (which might not be necessary for today's discussion)



In [1]:
import numpy as np #numpy package will be useful for most of the array operations in the code 
from sklearn.datasets import load_wine

In [2]:
#Let us load the wine data and store the result in X_y variable. The idea behind naming of the variable will be illustrated in the next few tabs.
X_y = load_wine()

In [7]:
#Let us print the contents of the X_y variable 

print(type(X_y))
print(X_y)


<class 'sklearn.utils.Bunch'>
{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [22]:
#So we found that the X_y variable is of type sklearn.utils.bunch
#further, we see that the X_y variable consists of dictionary-type structures named "data",  "target" and "target_names"

# Let us now segregate the data attributes and class labels into separate variables 

X = X_y.data
y = X_y.target

print('X shape:', X.shape, 'type(X):', type(X) )
print(' y shape:', y.shape, ' type(y):', type(y))



X shape: (178, 13) type(X): <class 'numpy.ndarray'>
 y shape: (178,)  type(y): <class 'numpy.ndarray'>


In [26]:
#Thus we see that X and y are numpy ndarrays. 
#We also see that there are 178 samples (or instances) in the data set and each sample has 13 attributes. 
#The shape of target variable y indicates that y contains the labels for these 178 samples

#We can print the unique labels available in y 
print(np.unique(y))

[0 1 2]


In [ ]:
# Let us also segregate the data set description into a different variable and check the contents
X_y_description = X_y.DESCR
print('type(X_y_description):', type(X_y_description))
print(X_y_description)

type(X_y_description): <class 'str'>
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.2

In [33]:
#Let us focus our discussion on the feature matrix X and keep aside the label matrix y for the time being.

#Let us compute two new matrices from X. 

XXT = np.matmul(X,np.transpose(X)) #X X^T matrix 
XTX = np.matmul(X.T,X) #X^T X matrix 

print('XXT shape:', XXT.shape, 'XTX shape:', XTX.shape)

print(X)

print(np.transpose(X))

XXT shape: (178, 178) XTX shape: (13, 13)
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[[1.423e+01 1.320e+01 1.316e+01 ... 1.327e+01 1.317e+01 1.413e+01]
 [1.710e+00 1.780e+00 2.360e+00 ... 4.280e+00 2.590e+00 4.100e+00]
 [2.430e+00 2.140e+00 2.670e+00 ... 2.260e+00 2.370e+00 2.740e+00]
 ...
 [1.040e+00 1.050e+00 1.030e+00 ... 5.900e-01 6.000e-01 6.100e-01]
 [3.920e+00 3.400e+00 3.170e+00 ... 1.560e+00 1.620e+00 1.600e+00]
 [1.065e+03 1.050e+03 1.185e+03 ... 8.350e+02 8.400e+02 5.600e+02]]


$XX^\top$ and $X^\top X$ are called covariance matrices. 

In particular, $XX^\top$ is of shape $\textit{num samples} \times \textit{num samples}$ and captures the correlation (upto scaling) between distinct samples in the data set. Hence we call $XX^\top$ to be sample covariance matrix. 

Similarly, $X^\top X$ is of shape $\textit{num features} \times \textit{num features}$ and captures the correlation (upto scaling) between different attributes in the data set.  Hence we call $X^\top X$ to be feature covariance matrix. 

In fact, these covariance matrices satisfy several important properties: 



1.   $XX^\top$ and $X^\top X$ are square and symmetric  
2.   $XX^\top$ and $X^\top X$ are positive semi-definite (that is, their eigen values are non-negative)
3.   $XX^\top$ and $X^\top X$ have same positive eigen values.  
4.   $XX^\top$ and $X^\top X$ have the same rank as $X$ 

Let us quickly check each of these facts. 


In [36]:
#checking if XXT and XTX are square and symmetric


print('XXT matrix:')
if XXT.shape[0] == XXT.shape[1]:
  print('XXT is square')
else:
  print('XXT is not square')

if np.all(XXT == XXT.T):
  print('XXT is symmetric')
else:
  print('XXT is not symmetric')


print('XTX matrix:')
if XTX.shape[0] == XTX.shape[1]:
  print('XTX is square')
else:
  print('XTX is not square')

if np.all(XTX == XTX.T):
  print('XTX is symmetric')
else:
  print('XTX is not symmetric')



XXT matrix:
XXT is square
XXT is symmetric
XTX matrix:
XTX is square
XTX is symmetric


In [37]:
#checking if XXT and XTX are positive semi-definite
#First we will use linalg.eig in numpy, which can be used to find eigen values and eigen vectors for any square matrix

print('eigen values of XXT:')
eig_val_XXT, eig_vec_XXT = np.linalg.eig(XXT)
print(eig_val_XXT)

print('eigen values of XTX:')
eig_val_XTX, eig_vec_XTX = np.linalg.eig(XTX)
print(eig_val_XTX)


eigen values of XXT:
[ 1.18519582e+08+0.00000000e+00j  2.43603495e+05+0.00000000e+00j
  3.26599028e+03+0.00000000e+00j  9.06017549e+02+0.00000000e+00j
  3.43836011e+02+0.00000000e+00j  2.09178961e+02+0.00000000e+00j
  1.21794126e+02+0.00000000e+00j  2.79829387e+01+0.00000000e+00j
  1.98611790e+01+0.00000000e+00j  1.27825659e+01+0.00000000e+00j
  6.76635454e+00+0.00000000e+00j  3.94740676e+00+0.00000000e+00j
  1.47358714e+00+0.00000000e+00j -1.21485711e-08+0.00000000e+00j
  6.07006165e-09+7.48821506e-09j  6.07006165e-09-7.48821506e-09j
 -2.44843502e-09+8.44958710e-09j -2.44843502e-09-8.44958710e-09j
  6.05133352e-09+0.00000000e+00j -5.84159307e-09+0.00000000e+00j
  1.83352726e-09+5.12116458e-09j  1.83352726e-09-5.12116458e-09j
 -5.14421605e-09+0.00000000e+00j -6.20504969e-10+5.17089683e-09j
 -6.20504969e-10-5.17089683e-09j  4.83675532e-09+0.00000000e+00j
  2.82559893e-09+3.56667005e-09j  2.82559893e-09-3.56667005e-09j
 -2.21991728e-09+3.66158223e-09j -2.21991728e-09-3.66158223e-09j
  3.

## Important note about the results obtained from $\texttt{np.linalg.eig}$## 

Note that the results from $\texttt{np.linalg.eig}$ show complex eigen values for $XX^\top$ matrix. 

However from theory if $A$ is a real symmetric matrix, then the eigen values need to be real. We present a proof of the result below. 

So, the results from $\texttt{np.linalg.eig}$ are due to numerical errors due to floating point approximations and truncations involved in the algorithms used to compute the eigen values and eigen vectors. 


$\textbf{Result:}$ If $A$ is a real symmetric matrix, then the eigen values are real. 

A simple proof is as below: 

Let $\lambda$ be a complex number of the form $a+bi$ which is an eigen value for a real symmetric matrix $A$ corresponding to the eigen vector $x\neq \mathbf{0}$. Recall that the complex conjugate $\bar{\lambda}$ of $\lambda$ is given by $a-bi$. 

Then we have:

$
\begin{align}
Ax &= \lambda x \nonumber \\
\text{Taking complex conjugates } & \text { on both sides, we have} \nonumber \\
\overline{Ax} &= \overline{\lambda x} \nonumber \\
\bar{A} \bar{x} &= \bar{\lambda} \bar{x} \nonumber \\
\end{align}
$

However $\bar{A} = A$ since $A$ is real. Thus we have $A\bar{x} = \bar{\lambda} \bar{x}$. Hence $\bar{x} \neq \mathbf{0}$ is an eigen vector of $A$ with a corresponding eigen value $\bar{\lambda}$.   

Now consider $A \bar{x} = \lambda \bar{x}$. Pre-multiplying by $x^\top$ we have:

$
\begin{align}
x^\top A \bar{x} &= \lambda x^\top \bar{x} \nonumber \\
(Ax)^\top \bar{x} &= \lambda x^\top \bar{x} \nonumber \\
\implies (\lambda x)^\top \bar{x} &= \lambda x^\top \bar{x} \nonumber \\
\lambda x^\top \bar{x} &= \lambda x^\top \bar{x} \nonumber \\
\end{align}
$

Since $r=x^\top \bar{x} \neq 0$ is a real quantity $\textbf{(check this!)}$ we have:   $\lambda r=\bar{\lambda} r \implies \lambda =\bar{\lambda}$. 

Now $\lambda = \bar{\lambda} \implies a+bi = a-bi$ is possible if and only if $b=0$ or $\lambda$ is a real number. Hence the proof follows. 

In [ ]:
#checking if XXT and XTX are positive semi-definite
#we will use linalg.eigh in numpy, which can be useful for symmetric matrices 

print('eigen values of XXT:')
eig_val_XXT, eig_vec_XXT = np.linalg.eigh(XXT)
print(eig_val_XXT)

print('eigen values of XTX:')
eig_val_XTX, eig_vec_XTX = np.linalg.eigh(XTX)
print(eig_val_XTX)


eigen values of XXT:
[-3.36866745e-08 -1.50220377e-08 -1.48359545e-08 -1.27703210e-08
 -1.12251019e-08 -8.61716632e-09 -7.68185582e-09 -6.08380757e-09
 -5.20923555e-09 -4.79181820e-09 -4.64584954e-09 -4.45823382e-09
 -4.06583460e-09 -3.76302785e-09 -3.52082671e-09 -3.48366439e-09
 -3.19645170e-09 -3.10620238e-09 -2.93389846e-09 -2.77958523e-09
 -2.56766319e-09 -2.50504266e-09 -2.30319114e-09 -2.20061929e-09
 -2.14217319e-09 -2.08954272e-09 -1.96743185e-09 -1.84108486e-09
 -1.80269071e-09 -1.71241283e-09 -1.51163812e-09 -1.48936809e-09
 -1.48435290e-09 -1.35417436e-09 -1.24807262e-09 -1.22321156e-09
 -1.20566808e-09 -1.13322046e-09 -1.11424634e-09 -1.09010928e-09
 -1.08372074e-09 -1.06103073e-09 -1.03223767e-09 -9.47104518e-10
 -9.09229967e-10 -8.51452866e-10 -8.02550788e-10 -7.64072662e-10
 -7.60879699e-10 -7.10046986e-10 -7.09985259e-10 -6.32793396e-10
 -6.23683235e-10 -6.11804021e-10 -5.96182200e-10 -5.64414286e-10
 -5.50822138e-10 -5.22651034e-10 -5.18204553e-10 -4.73363967e-10
 -4.

## Important note about the results obtained from $\texttt{np.linalg.eigh}$## 

Note that the results from $\texttt{np.linalg.eigh}$ show some negative eigen values for $XX^\top$ matrix. 

However from theory, we know that if $A$ is a $n \times n$ symmetric and positive semi-definite matrix, then  the eigen values are non-negative. 

A proof of this result is given below. 

Hence the results from $\texttt{np.linalg.eigh}$ should be interpreted carefully. The negative values are again due to numerical errors in algorithms. 



$\mathbf{Result:}$ If $A$ is a $n \times n$ symmetric and positive semi-definite matrix, then  the eigen values are non-negative. 


$\textbf{Recall:}$ Since $A$ is symmetric and positive semi-definite, we know that $x^\top Ax\geq 0$ for any $x \in {\mathbb{R}}^n$. 

Now consider $v \neq \mathbf{0}$ as an eigen vector of $A$ with eigen value $\lambda$, we have: $Av = \lambda v$. 

Then we have by pre-multiplying by $v^\top$:

$
\begin{align}
v^\top Av &= v^\top (\lambda v) \nonumber \\
\implies \lambda v^\top  v &\geq 0 \nonumber 
\end{align}
$

Since we know that for a vector $v=\begin{bmatrix}
v_1 \\
v_2 \\
\vdots \\
v_n
\end{bmatrix} \in {\mathbb{R}}^n$, we have $v^\top v = \|v\|_2^2 = \sum_{i=1}^{n} v_i^2 \geq 0$ . 

Since $v \neq \mathbf{0}$, we have $\|v\|_2^2 > 0$. 

Thus  from $\lambda v^\top  v \geq 0$ and $v^\top v > 0$, we have $\lambda  \geq 0$. 

In [38]:
#checking if XXT and XTX are have same positive eigen values 
#we will use linalg.eigh in numpy, which can be useful for symmetric matrices 

print('positive eigen values of XXT:')
eig_val_XXT,_ = np.linalg.eigh(XXT)
print( eig_val_XXT[np.where(eig_val_XXT > 0)])


print('positive eigen values of XXT:')
eig_val_XTX,_ = np.linalg.eigh(XTX)
print( eig_val_XTX[np.where(eig_val_XTX > 0)])


positive eigen values of XXT:
[1.19619165e-11 1.98509559e-11 4.81003319e-11 5.50650362e-11
 1.05864068e-10 1.08420716e-10 1.26845060e-10 1.32200620e-10
 1.63387440e-10 1.64194831e-10 1.71001422e-10 1.91018311e-10
 1.99437077e-10 2.55970367e-10 2.61623591e-10 2.92526690e-10
 2.94281569e-10 2.99684548e-10 3.19319082e-10 3.61034601e-10
 3.66223500e-10 3.79407573e-10 4.44199084e-10 4.62446296e-10
 4.71147017e-10 5.12191237e-10 5.47294991e-10 5.51349781e-10
 5.57445546e-10 6.20194840e-10 6.22536313e-10 6.70473051e-10
 6.87591180e-10 7.62130803e-10 7.82826751e-10 8.44170375e-10
 8.80089159e-10 9.46222583e-10 9.95613391e-10 9.97965138e-10
 1.06415963e-09 1.07001197e-09 1.09796732e-09 1.14113850e-09
 1.23035395e-09 1.34984892e-09 1.36565621e-09 1.40590431e-09
 1.50153880e-09 1.56055664e-09 1.72382377e-09 1.74096149e-09
 1.76624627e-09 2.16224095e-09 2.33035521e-09 2.35834990e-09
 2.52488531e-09 2.81836724e-09 2.90043644e-09 2.93426979e-09
 3.31926660e-09 3.41868192e-09 4.09815682e-09 4.2008801

##Note about the precision of eigen values:## 

Please note that there are a few positive eigen values which are close to zero. However in this case, we can guarantee that these values should be zero. 

These issues highlight some numerical issues when computing eigen values and eigen vectors using $\texttt{numpy.linalg.eig}$ and $\texttt{numpy.linalg.eigh}$. 



In [39]:
#check rank of matrices XXT and XTX 

print('rank(XXT):', np.linalg.matrix_rank(XXT), 'rank(XTX):', np.linalg.matrix_rank(XTX))

rank(XXT): 13 rank(XTX): 13


## Rank of matrix $A$ :## 

Note that for a matrix $A$ of size $m \times n$, $rank(A)$ is defined as the number of linearly independent rows or columns in $A$. 

Hence $rank(A) \leq \min\{m,n\}$. 

If $rank(A) = \min\{m,n\}$ then the matrix is called full rank. 

Note that for $\textit{wine}$ data set, we have $X^\top X$ to be of size $13 \times 13$. Also note that $rank(X^\top X)=13$, hence $X^\top X$ is full-rank. 

## Checking alignment of sample features using dot products ## 

In [ ]:
#Take some samples of the same class 

X_class0 = X[np.where(y==0),:].squeeze()
print(X_class0.shape)

X_class1 = X[np.where(y==1),:].squeeze()
print(X_class1.shape)


X_class2 = X[np.where(y==2),:].squeeze()
print(X_class2.shape)


(59, 13)
(71, 13)
(48, 13)


In [ ]:
#Let us find the dot product between some samples of class 0
print(np.dot(X_class0[0]/np.linalg.norm(X_class0[0]),X_class0[1]/np.linalg.norm(X_class0[1])) )

0.9997092287724737


In [ ]:
#Let us find the dot product between some samples of class 1
print(np.dot(X_class1[30]/np.linalg.norm(X_class1[30]),X_class1[42]/np.linalg.norm(X_class1[42])) )

0.9990245635883316


In [ ]:
#Let us find the dot product between some samples of class 2
print(np.dot(X_class2[20]/np.linalg.norm(X_class2[20]),X_class2[32]/np.linalg.norm(X_class2[32])) )

0.9982866107350962


In [ ]:
#Let us find the dot product between some samples of class 0 and class 2
print(np.dot(X_class0[0]/np.linalg.norm(X_class0[0]),X_class1[10]/np.linalg.norm(X_class1[10])) )

0.9960370718188822


## Exercise ## 

Try the above code functionalities on $\textit{iris}$ data set from $\texttt{scikit-learn}$ package. 